project:
  type: website
  output-dir: docs

website:
  title: "Data Literacy Course Redesign Institute"
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - monday.qmd
      - tuesday.qmd
      - wednesday.qmd
      - thursday.qmd
      - friday.qmd
      - section: "Slides"
        contents:
          - text: "01 intro"
            file: slides/01_intro.pdf
          - text: "02 digital humanities"
            file: slides/02_digital_humanities.pdf
          - text: "03 data"
            file: slides/03_data.pdf
          - text: "04 grammar of graphics"
            file: slides/04_grammar_of_graphics.pdf
          - text: "05 data art"
            file: slides/05_data_art.pdf
          - text: "06 data visualization tools"
            file: slides/06_viz_tools.pdf
          - text: "07 tidy data"
            file: slides/07_tidy_data.pdf
          - text: "08 text analysis"
            file: slides/08_text_analysis.pdf
          - text: "09 algorithmic accountability"
            file: slides/09_algorithms.pdf
          - text: "10 mapping basics"
            file: slides/10_mapping.basics.pdf
          - text: "11 communcation"
            file: slides/11_communicate.pdf
          - text: "12 machinery of the web"
            file: slides/12_machinery_of_the_web.pdf
          - text: "13 why not AI?"
            file: slides/13_why_not_AI.pdf
      - section: "Activities"
        contents:
          - syllabus_review.qmd
          - finding_data.qmd
          - unpacking_charts.qmd
          - handmade_viz.qmd
          - datawrapper.qmd
          - unpacking_headlines.qmd
          - analyzing_data.qmd
          - reading_storymaps.qmd
          - making_storymaps.qmd
          - GitHubPages.qmd
          


format:
  html:
    theme: cosmo

editor: visual

