project:
  type: website
  output-dir: docs
  

website:
  title: "Data Literacy Course (Re)Design Institute"
  description: "Materials from the May 20-24, 2024 Data Literacy Course (Re)Design Institute at Tulane University"
  page-footer: "[CC BY](https://creativecommons.org/licenses/by/4.0/) Amelia McNamara" 
  site-url: "https://ameliamn.github.io/TulaneDataLiteracy"
  twitter-card: true
  open-graph: true
  image: "img/jannekestaaks.jpg"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Daily schedules and resources"
        contents:
        - monday.qmd
        - tuesday.qmd
        - wednesday.qmd
        - thursday.qmd
        - friday.qmd
      - section: "Activities"
        contents:
          - syllabus_review.qmd
          - finding_data.qmd
          - unpacking_charts.qmd
          - handmade_viz.qmd
          - datawrapper.qmd
          - unpacking_headlines.qmd
          - analyzing_data.qmd
          - reading_storymaps.qmd
          - making_storymaps.qmd
          - GitHubPages.qmd
      - section: "Resources"
        contents:
          - text: "For learning R"
            href: learning_R.qmd
          - text: "For learning Tableau"
            href: learning_Tableau.qmd
      - section: "Slides"
        contents:
          - text: "Slide overview"
            href: slides.qmd
          - section: "Slide downloads"
            contents:
              - text: "01 intro"
                file: slides/01_intro.pdf
              - text: "02 digital humanities"
                file: slides/02_digital_humanities.pdf
              - text: "03 data"
                file: slides/03_data.pdf
              - text: "04 grammar of graphics"
                file: slides/04_grammar_of_graphics.pdf
              - text: "05 data art"
                file: slides/05_data_art.pdf
              - text: "06 data visualization tools"
                file: slides/06_viz_tools.pdf
              - text: "07 tidy data"
                file: slides/07_tidy_data.pdf
              - text: "08 text analysis"
                file: slides/08_text_analysis.pdf
              - text: "09 algorithmic accountability"
                file: slides/09_algorithms.pdf
              - text: "10 mapping basics"
                file: slides/10_mapping_basics.pdf
              - text: "11 communcation"
                file: slides/11_communicate.pdf
              - text: "12 machinery of the web"
                file: slides/12_machinery_of_the_web.pdf
              - text: "13 why not AI?"
                file: slides/13_why_not_AI.pdf
     
          


format:
  html:
    theme: cosmo

editor: visual

