## Data Literacy Course (Re)Design Institute Description {#about-the-course .unnumbered}

##### May 20-24, 2024

#### [Tulane University](https://tulane.edu/), co-sponsored by the [Center for Engaged Learning & Teaching](https://celt.tulane.edu/) (CELT) and the [Connolly Alexander Institute for Data Science](https://datainstitute.tulane.edu/) (CAIDS)

### Leader

Dr. Amelia McNamara (she/her), `amelia.mcnamara@stthomas.edu`

### Institute description

This weeklong in-person institute will provide faculty from across a variety of disciplines the knowledge, resources, and support to (re)design a course infused with data literacy principles. Participants will leave with an understanding of digital and data technologies that could be introduced into their courses, sample assignments promoting data literacy, and a new or revised syllabus.

#### Institute goals

-   Learn to identify data products, conceptualize of data structure, and find appropriate data for tasks online.
-   Frame disciplinary questions as data questions, both from a professional (research) lens and at the instructional level.
-   Experience new tools for data, including [Datawrapper](https://www.datawrapper.de/) for data visualization, [Excel online](https://www.microsoft365.com/launch/Excel/) for data collection and analysis, [Voyant Tools](https://voyant-tools.org/) for text data analysis, [StoryMaps](https://storymaps.arcgis.com/) for mapping and communication, [GitHub Pages](https://pages.github.com/) for simple webhosting and portfolio presentation, and LMMs like [ChatGPT](https://chatgpt.com/) as a potential learning tool. Begin developing technical skills in these tools.
-   Engage in sample data literacy assignments, including What's Going On in This Graph?, Hand Drawn Data Visualization, Data Exhaust, Data Ethics, and more.
-   Critique existing assignments and syllabi, and modify pedagogical materials to fit into an updated syllabus.

## Tentative Schedule {#schedule .unnumbered}

The following is an outline of the institute. Please refer to the daily modules for more detailed information.

### Monday: Overview, data collection

Digital humanities across disciplines. Case studies from English, history, linguistics, others as relevant to institute participants. Connections to the rest of the week. Syllabus review. Read sample syllabi of data-infused courses, look at participant's syllabi for potential opportunities. Consider: What is data? How is it generated? Idea of data exhaust. How to find data? Searching online for relevant data, or retrieving data relevant to discipline/research area

### Tuesday: Data visualization

The Grammar of Graphics. How data connects to visual attributes. Reading graphics using the NY Times framework "What's Going On in This Graph?" Data art versus generative art. Hand-drawn data visualization. Electronic tools for data visualization. Example tool: [Datawrapper](https://www.datawrapper.de/).

### Wednesday: Data analysis

Tidy data and concepts of data wrangling. Unpacking newspaper headlines for underlying data. Data analysis basics. Example tool: [Excel online](https://www.microsoft365.com/launch/Excel/). Text as data. Topic modeling, word embeddings. Example tool: [Voyant Tools](https://voyant-tools.org/). Most relevant data/wrangling/analysis for discipline. Algorithmic accountability and digital ethics. Connection to text analysis and LMMs. Data/digital ethics in disciplines. How can this be integrated into courses?

### Thursday: Communication and presentation

Communicating results digitally. Data journalism, digital portfolios. Reading StoryMaps and discussing connections to disciplines. Mapping basics. Example tool: [StoryMaps](https://storymaps.arcgis.com/). The machinery of the web. Example tool: [GitHub Pages](https://pages.github.com/). Curriculum/syllabus review. Where do students see these skills? Are they necessary? LLMs. Ethics-- electricity, water use, copyright/fair use. Example tool: [ChatGPT](https://chatgpt.com/). How could LMMs be used as learning tools? Discuss syllabus statements.

### Friday: Finalizing the connections

Ideas for curricular integration. Successes/blockers. Ideas and resources. Presentations, reflection and wrap-up.

## Syllabus statements

These are two of my commonly-used syllabus statements that felt relevant to this institute. I'm providing them both as a jumping-off-point for institute ground rules and as inspiration for your syllabus statements.

### Inclusive classroom

Because data is collected by and about humans, it always encodes our viewpoints and biases. As a result, this course will likely touch upon difficult topics related to race, gender, inequality, class, and oppression.

We each come into this class with different perspectives that can be shared to enhance our understanding of these issues. I ask that you enter these conversations with respect, curiosity, and cultural humility. You should be open to alternative perspectives and willing to revise beliefs that are based on misinformation. As a general rule, your ideas and experiences can always be shared during these conversation but refrain from dismissing the experiences of others.

Please plan to treat me and your classmates with respect. To me, respect includes using peoples’ pronouns and preferred name (both for me and for your classmates), arriving at class on time or coming in quietly if you are late, and focusing on the task at hand. Of course, personal attacks of any kind will not be tolerated.

### Collaboration and generative AI

The goal of this course is to help you develop and strengthen your skills as a data communicator. It is acceptable to work collaboratively with other students, or use generative AI (such as ChatGPT) to help you understand topics, debug code, and clean up written work. However, I expect all work submitted to be **substantively yours**. This means that copying and pasting large blocks of code or major textual elements from another student, internet websites, or generative AI systems, is not acceptable. If I suspect work you submitted is not substantively yours, I may ask you to come in and discuss the work with me. If you cannot explain how you arrived at the solution, and restate the work in your words, you will receive no credit. All students are bound by the Undergraduate Student Academic Integrity Policy. Cases of dishonesty, plagiarism, etc., will be reported to the dean.
